{% set name = "compas_fab" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9074dfe324c7f3cb5b294a1fce8789b0f22d91ddaed697827706ad720073feb1

build:
  # Fix conda issue with location of vrep shared libraries path
  binary_relocation: false
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - compas >=1.1,<2.0
    - roslibpy >=1.1.0
    - pyserial
    - bullet   # (should technically be pybullet, but currently not in conda)

test:
  imports:
    - compas_fab
    - compas_fab.backends   # [not linux]
    - compas_fab.robots
    - compas_fab.rhino
    - compas_fab.blender

about:
  home: https://github.com/compas-dev/compas_fab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Robotic fabrication package for the COMPAS Framework
  description: |
    Robotic fabrication package for the COMPAS Framework facilitating the
    planning and execution of robotic fabrication processes. It provides
    interfaces to existing software libraries and tools available in the
    field of robotics (e.g. OMPL, ROS, PyBullet) and makes them accessible
    from within the parametric design environment. The package builds upon
    COMPAS (https://compas.dev), an open-source Python-based framework for
    collaboration and research in architecture, engineering and digital fabrication.
  doc_url: https://gramaziokohler.github.io/compas_fab
  dev_url: https://github.com/compas-dev/compas_fab

extra:
  recipe-maintainers:
    - gonzalocasas
    - beverlylytle
    - romanarust
